site_name: Nexus Event Sourcing Library
site_url: https://nexus-mods.github.io/NexusMods.EventSourcing/

repo_name: Nexus-Mods/NexusMods.Archives.Nx
repo_url: https://github.com/Nexus-Mods/NexusMods.EventSourcing

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Nexus-Mods
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TheSewer56

extra_css:
  - Nexus/Stylesheets/extra.css

plugins:
  - search

markdown_extensions:
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist
  - def_list
  - meta
  - md_in_html
  - attr_list
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

theme:
  name: material
  palette:
    scheme: nexus-slate
  features:
    - navigation.instant

nav:
  - Home: index.md
  - Index Format: IndexFormat.md
  - Value Format: ValueFormat.md
  - Schema Changes: SchemaChanges.md

