// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NexusMods.MnemonicDB.SourceGenerator
{
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class ModelTemplate : ModelTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\nusing Microsoft.Extensions.DependencyInjection;\r\nusing __MODELS__ = global::NexusMods.MnemonicDB.Abstractions.Models;\r\nusing __ABSTRACTIONS__ = global::NexusMods.MnemonicDB.Abstractions;\r\nusing __DI__ = Microsoft.Extensions.DependencyInjection;\r\n\r\n\r\nnamespace ");
            
            #line 11 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public class ");
            
            #line 13 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write(" : __MODELS__.ITemporaryEntity\r\n    {\r\n        public static class Attributes\r\n        {\r\n               private const string __ns__ = \"");
            
            #line 17 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Namespace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 17 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("\";\r\n\r\n");
            
            #line 19 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"

foreach (var attribute in Model.Attributes)
{

            
            #line default
            #line hidden
            this.Write("               public static readonly global::");
            
            #line 23 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Type.ToDisplayString()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 23 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name));
            
            #line default
            #line hidden
            this.Write(" = new(__ns__, nameof(");
            
            #line 23 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name));
            
            #line default
            #line hidden
            this.Write(")) ");
            
            #line 23 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.AttributePostfix));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 24 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"

}

            
            #line default
            #line hidden
            this.Write("               // References\r\n");
            
            #line 28 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"

foreach (var reference in Model.References)
{
    if (reference.MultiCardinality)
    {

            
            #line default
            #line hidden
            this.Write("               public static readonly global::NexusMods.MnemonicDB.Abstractions.Attributes.ReferencesAttribute ");
            
            #line 34 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(reference.Name));
            
            #line default
            #line hidden
            this.Write("Ids = new(__ns__, \"");
            
            #line 34 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(reference.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n");
            
            #line 35 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"

    }
    else
    {

            
            #line default
            #line hidden
            this.Write("               public static readonly global::NexusMods.MnemonicDB.Abstractions.Attributes.ReferenceAttribute ");
            
            #line 40 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(reference.Name));
            
            #line default
            #line hidden
            this.Write("Id = new(__ns__, \"");
            
            #line 40 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(reference.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n");
            
            #line 41 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"

    }
}

            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n        public ");
            
            #line 47 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("(__ABSTRACTIONS__.ITransaction tx)\r\n        {\r\n            Id = tx.TempId();\r\n            tx.Attach(this);\r\n        }\r\n\r\n        public ");
            
            #line 53 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("(__ABSTRACTIONS__.ITransaction tx, __ABSTRACTIONS__.EntityId id)\r\n        {\r\n            Id = id;\r\n            tx.Attach(this);\r\n        }\r\n\r\n        public ");
            
            #line 59 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("ReadModel Remap(__ABSTRACTIONS__.ICommitResult result)\r\n        {\r\n            return new ");
            
            #line 61 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("ReadModel(result.Db, result[Id]);\r\n        }\r\n\r\n\r\n        public __ABSTRACTIONS__.EntityId Id { get; private set; }\r\n\r\n");
            
            #line 67 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"

foreach (var attribute in Model.Attributes)
{

            
            #line default
            #line hidden
            this.Write("        public required ");
            
            #line 71 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.TypeInfo!.HighLevel.ToDisplayString()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 71 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name));
            
            #line default
            #line hidden
            this.Write(" { get; init; }\r\n");
            
            #line 72 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"

}

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 76 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"

foreach (var reference in Model.References)
{
    if (reference.MultiCardinality)
    {

            
            #line default
            #line hidden
            this.Write("        public required __ABSTRACTIONS__.EntityId[] ");
            
            #line 82 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(reference.Name));
            
            #line default
            #line hidden
            this.Write("Ids { get; init; }\r\n");
            
            #line 83 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"

    }
    else
    {

            
            #line default
            #line hidden
            this.Write("        public required __ABSTRACTIONS__.EntityId ");
            
            #line 88 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(reference.Name));
            
            #line default
            #line hidden
            this.Write("Id { get; init; }\r\n");
            
            #line 89 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"

    }
}

            
            #line default
            #line hidden
            this.Write("\r\n\r\n    public static implicit operator __ABSTRACTIONS__.EntityId(");
            
            #line 95 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write(" self) => self.Id;\r\n\r\n    public void AddTo(__ABSTRACTIONS__.ITransaction tx)\r\n    {\r\n");
            
            #line 99 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"

foreach (var attribute in Model.Attributes)
{

            
            #line default
            #line hidden
            this.Write("         tx.Add(Id, Attributes.");
            
            #line 103 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 103 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 104 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"

}

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 108 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"

foreach (var attribute in Model.References)
{
    if (attribute.MultiCardinality)
    {

            
            #line default
            #line hidden
            this.Write("         tx.Add(Id, Attributes.");
            
            #line 114 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name));
            
            #line default
            #line hidden
            this.Write("Ids, ");
            
            #line 114 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name));
            
            #line default
            #line hidden
            this.Write("Ids);\r\n");
            
            #line 115 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"

    }
    else
    {

            
            #line default
            #line hidden
            this.Write("         tx.Add(Id, Attributes.");
            
            #line 120 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name));
            
            #line default
            #line hidden
            this.Write("Id, ");
            
            #line 120 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name));
            
            #line default
            #line hidden
            this.Write("Id);\r\n");
            
            #line 121 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"

    }
}

            
            #line default
            #line hidden
            this.Write("    }\r\n\r\n    public static ");
            
            #line 127 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("ReadModel Get(__ABSTRACTIONS__.IDb db, __ABSTRACTIONS__.EntityId id)\r\n    {\r\n        return new ");
            
            #line 129 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("ReadModel(db, id);\r\n    }\r\n\r\n    public static IEnumerable<");
            
            #line 132 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("ReadModel> Get(__ABSTRACTIONS__.IDb db, IEnumerable<__ABSTRACTIONS__.EntityId> ids)\r\n    {\r\n        foreach (var id in ids)\r\n        {\r\n            yield return Get(db, id);\r\n        }\r\n    }\r\n}\r\n\r\npublic class ");
            
            #line 141 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("ReadModel(__ABSTRACTIONS__.IDb db, __ABSTRACTIONS__.EntityId id) : __MODELS__.ReadOnlyModel(db, id)\r\n{\r\n\r\n");
            
            #line 144 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"

foreach (var attribute in Model.Attributes)
{

            
            #line default
            #line hidden
            this.Write("    public ");
            
            #line 148 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.HighLevelType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 148 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name));
            
            #line default
            #line hidden
            this.Write(" => ");
            
            #line 148 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write(".Attributes.");
            
            #line 148 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name));
            
            #line default
            #line hidden
            this.Write(".Get(this);\r\n");
            
            #line 149 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"

}

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 153 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"

foreach (var reference in Model.References)
{
    if (reference.MultiCardinality)
    {

            
            #line default
            #line hidden
            this.Write("    public IEnumerable<__ABSTRACTIONS__.EntityId> ");
            
            #line 159 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(reference.Name));
            
            #line default
            #line hidden
            this.Write("Ids => ");
            
            #line 159 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write(".Attributes.");
            
            #line 159 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(reference.Name));
            
            #line default
            #line hidden
            this.Write("Ids.Get(this);\r\n");
            
            #line 160 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"

    }
    else
    {

            
            #line default
            #line hidden
            this.Write("    public __ABSTRACTIONS__.EntityId ");
            
            #line 165 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(reference.Name));
            
            #line default
            #line hidden
            this.Write("Id => ");
            
            #line 165 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write(".Attributes.");
            
            #line 165 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(reference.Name));
            
            #line default
            #line hidden
            this.Write("Id.Get(this);\r\n\r\n    public ");
            
            #line 167 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(reference.ReferenceModelName));
            
            #line default
            #line hidden
            this.Write("ReadModel ");
            
            #line 167 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(reference.Name));
            
            #line default
            #line hidden
            this.Write(" => new ");
            
            #line 167 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(reference.ReferenceModelName));
            
            #line default
            #line hidden
            this.Write("ReadModel(Db, ");
            
            #line 167 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(reference.Name));
            
            #line default
            #line hidden
            this.Write("Id);\r\n");
            
            #line 168 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"

    }
}

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 173 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"

foreach (var backRef in Model.BackRefs)
{

            
            #line default
            #line hidden
            this.Write("    public IEnumerable<");
            
            #line 177 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(backRef.OtherModelName));
            
            #line default
            #line hidden
            this.Write("ReadModel> ");
            
            #line 177 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(backRef.ThisAttributeName));
            
            #line default
            #line hidden
            this.Write("\r\n   {\r\n      get {\r\n         foreach (var id in Db.GetBackRefs(");
            
            #line 180 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(backRef.OtherModel));
            
            #line default
            #line hidden
            this.Write(".Attributes.");
            
            #line 180 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(backRef.OtherAttributeName));
            
            #line default
            #line hidden
            this.Write("Id, Id))\r\n         {\r\n            yield return ");
            
            #line 182 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(backRef.OtherModelName));
            
            #line default
            #line hidden
            this.Write(".Get(Db, id);\r\n         }\r\n      }\r\n   }\r\n");
            
            #line 186 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"

}

            
            #line default
            #line hidden
            this.Write("}\r\n\r\npublic static class ");
            
            #line 191 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("Extensions\r\n{\r\n    public static __DI__.IServiceCollection Add");
            
            #line 193 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("Model(this __DI__.IServiceCollection collection)\r\n    {\r\n");
            
            #line 195 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"

foreach (var attribute in Model.Attributes)
{

            
            #line default
            #line hidden
            this.Write("        collection.AddSingleton<__ABSTRACTIONS__.IAttribute>(");
            
            #line 199 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write(".Attributes.");
            
            #line 199 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 200 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"

}

            
            #line default
            #line hidden
            
            #line 203 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"

foreach (var attribute in Model.References)
{

            
            #line default
            #line hidden
            this.Write("        collection.AddSingleton<__ABSTRACTIONS__.IAttribute>(");
            
            #line 207 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write(".Attributes.");
            
            #line 207 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.AttributeName));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 208 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"

}

            
            #line default
            #line hidden
            this.Write("        return collection;\r\n    }\r\n}\r\n\r\n\r\n\r\n}\r\n\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 220 "C:\oss\NexusMods.MnemonicDB\src\NexusMods.MnemonicDB.SourceGenerator\ModelTemplate.tt"

    public ConcreteModel Model;

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class ModelTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
